version: '3.9'
services:
  odt:
    container_name: outsidedigital_backend
    profiles: [ "prod" ]
    build:
      dockerfile: Dockerfile
      context: .
    image: odt
    env_file:
      - .env.prod
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    profiles: [ "dev", "prod" ]
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
      POSTGRES_DB: nest
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  test-db:
    profiles: [ "test" ]
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - postgres

  pgadmin:
    profiles: [ "dev" ]
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
